### ISSUE TITLE
Can i Use it

### ISSUE THREAD

**Issue by conradKE** [nitishsai9/Covid19LiveTrackerApp#1]
can i fork it and use it

**Comment by nitishsai9** [comment]
U can use it other than commercial purpose or in play store.

**Comment by nitishsaik** [comment]
U can use it but not for commercial purpose or resale or publishing it in playstore without my consent.

**Comment by conradKE** [comment]
okay.. thanks

**Comment by conradKE** [comment]
hey boss can you help me with the link where you are getting data

**Comment by nitishsaik** [comment]
i have made my own api by scraping worldmeter and govt of india website

**Comment by conradKE** [comment]
thats awesome let see what i can do i wana also develop a tracking app based on our country
